# Dependabot configuration file.
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2

enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "http"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "http_browser"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "http_io"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "http_redirect"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "http_test"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "repo_support"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
