targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - test/multiplatform/**_test.dart
          - test/web/**_test.dart
          - web/**.dart
#      build_vm_compilers|entrypoint:
#        generate_for:
#          - test/multiplatform/**_test.dart
#          - test/vm/**_test.dart
#          - bin/**.dart